spring:
  profiles:
    active: development
  application:
    name: FuelCompense
  datasource:
    driver-class-name: org.postgresql.Driver
    username:
    password:
    url: jdbc:postgresql://localhost:5432/fuelcompense
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  server:
    port: 8080